DROP DATABASE IF EXISTS compta;
CREATE DATABASE IF NOT EXISTS compta;
USE compta;


CREATE TABLE IF NOT EXISTS fournisseur (
    ID int(11) PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(25)
);


CREATE TABLE IF NOT EXISTS article (
    ID int(11) PRIMARY KEY AUTO_INCREMENT,
    REF VARCHAR(13),
    DESIGNATION VARCHAR(255),
    PRIX DECIMAL(7,2),
    ID_FOU int(11),
    FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID)
);


CREATE TABLE IF NOT EXISTS bon (
    ID int(11) PRIMARY KEY AUTO_INCREMENT,
    NUMERO int(11),
    DATE_CMDE DATETIME,
    DELAI int(11),
    ID_FOU int(11),
    FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID)
);

CREATE TABLE IF NOT EXISTS compo (
    ID int(11) PRIMARY KEY AUTO_INCREMENT,
    ID_ART int(11),
    ID_BON int(11),
    QTE int(11),
    FOREIGN KEY (ID_ART) REFERENCES article(ID),
    FOREIGN KEY (ID_BON) REFERENCES bon(ID)
);
